@baseUrl = http://localhost:3000/api

### Inscription d'un utilisateur
POST {{baseUrl}}/users
Content-Type: application/json

{ 
  "fullName": "",
  "email": "",
  "password": ""
}

### Connexion d'un utilisateur
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "",
  "password": ""
}

### Get user by id test
GET {{baseUrl}}/users/getByIndex/13
Content-Type: application/json

### Tester une route protégée (récupérer les infos de l'utilisateur connecté)
GET {{baseUrl}}/users/me
Authorization: Bearer TOKEN

### Changement de mot de passe d'un utilisateur connecté
POST {{baseUrl}}/users/changePassword
Content-Type: application/json
Authorization: Bearer TOKEN

{
  "oldPassword": "",
  "newPassword": ""
}

### Test de création d'évenement
POST {{baseUrl}}/events
Authorization: Bearer TOKEN
Content-Type: application/json

{
  "name": "",
  "organizerId": ,
  "startDate": "",
  "endDate": "",
  "address": "",
  "description": ""
}

### Test de récupération des événements
GET {{baseUrl}}/events
Authorization: Bearer TOKEN

### Test de création de Wallet
POST {{baseUrl}}/wallet
Content-Type: application/json

{
  "userId": ,
  "organizerId": ,
  "amount": 
}

### Test to get all wallets of a user
GET {{baseUrl}}/users/me/wallets
Authorization: Bearer TOKEN

### Test to decrypt a wallet qr code
POST {{baseUrl}}/decrypt-qr
Content-Type: application/json

{
  "encryptedData": ""
}

### Get my events
GET {{baseUrl}}/events/my
Authorization: Bearer TOKEN
Content-Type: application/json

### Add money to wallet
POST {{baseUrl}}/wallet/addMoney
Content-Type: application/json

{
  "walletId": ,
  "amount": 
}

### Affiche un event par rapport à son ID
GET {{baseUrl}}/events/1
Content-Type: application/json

### S'inscrire à un événement
POST {{baseUrl}}/events/8/register
Content-Type: application/json
Authorization: Bearer TOKEN

### Récupérer les logs (admin uniquement)
GET {{baseUrl}}/admin/logs
Authorization: Bearer TOKEN
