### Inscription d'un utilisateur
POST http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQwNjUyODMxfQ.drVFCAwIgy8XupuNUl1fi3gxzyk2UiHwgBdLcHb3rsU
Content-Type: application/json

{
  "fullName": "usertest2",
  "email": "usertest2@example.com",
  "password": "Secure12*",
  "fullName": "newuser",
  "email": "newusdser@example.com",
  "password": "Secsdure12*"
}

### Connexion d'un utilisateur
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "bobby@example.com",
  "password": "Abscdef12&*"
}


### Tester une route protégée (récupérer les infos de l'utilisateur connecté)
GET http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDksImlhdCI6MTc0MzYxNTAzMn0.L0Ctuk2pSdZ_gHon4xMVubzWPzGd3bpcSHRfONEon_o

### Changement de mot de passe d'un utilisateur connecté
POST http://localhost:3000/users/changePassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjIsImlhdCI6MTc0MzAxODc3Nn0.C0sN9pdrD0--zKclc-NTzSpOuGKf_2I24myUmchLjwY

{
  "oldPassword": "Secure12*",
  "newPassword": "NewSecure99!"
}

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQwNjUyODMxfQ.drVFCAwIgy8XupuNUl1fi3gxzyk2UiHwgBdLcHb3rsU

### Test de création d'évenement
POST http://localhost:3000/events
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQwNjUyODMxfQ.drVFCAwIgy8XupuNUl1fi3gxzyk2UiHwgBdLcHb3rsU
Content-Type: application/json

{
  "name":"test",
  "organizer":"huiezhfiufez",
  "startDate":"2025-06-15T14:30:00",
  "endDate":"2025-06-15T14:40:00",
  "adress":"somewhere",
  "description":"blablabla"
}

### Test de création de PaymentGroup

POST http://localhost:3000/payment-group
Content-Type: application/json

{
  "name": "Pirate Bay",
  "description": "Credits for all of our clubs downtown",
  "walletLink": "https://www.paypal.me/piratebay"
}

### Test de création de Wallet

POST http://localhost:3000/wallet
Content-Type: application/json

{
  "userId": 2,
  "paymentGroupId": 2,
  "amount": 90
}


### Test to get all wallets of a user
GET http://localhost:3000/users/me/wallets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQwNjUyODMxfQ.drVFCAwIgy8XupuNUl1fi3gxzyk2UiHwgBdLcHb3rsU