### Inscription d'un utilisateur
POST http://localhost:3000/users
Content-Type: application/json

{
  "fullName": "newuser",
  "email": "newuser@example.com",
  "password": "Secure12*"
}

### Connexion d'un utilisateur
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "Mickael2438@example.com",
  "password": "SecurePassword12349"
}

### Tester une route protégée (Remplace `TOKEN_ICI` par le token reçu après login)
GET http://localhost:3000/users/me
Authorization: Bearer TOKEN_ICI



### Tester une route protégée (récupérer les infos de l'utilisateur connecté)
GET http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzQwNjUyODMxfQ.drVFCAwIgy8XupuNUl1fi3gxzyk2UiHwgBdLcHb3rsU

